### ISSUE TITLE
Increase performance by reducing queries

### ISSUE THREAD

**Issue by alexanderweiss** [vinkla/translator#29]
Hi,

I'm currently using Translator in a project where on some requests I'm querying the database for about 200 translated objects (model instances). It's not very fast. So, looking at why it was slow, I found out that for each object (for which I'm getting just one language) Translator runs two queries, one to get the locales and one to get the actual translation.

Now, I've written a patch that caches the locales (basically halving the amount of queries in my case), which shaves of a quarter of a second for me. I'll happily create a pull request for it.

But I was also thinking about the querying for the translation. It'd be a lot better to be able to use something like `Group::with('translation')->get();`, which would again greatly reduce the amount of queries. A hasOne or hasMany relation might be used to achieve that:

```php
public function translation()
{
    return $this->hasOne($this->translator)->where('locale_id', $this->getLocaleId());
}
```
In combination with adding the translation to the `$hidden` array to prevent it from being included in Array/JSON output. I'm not sure if this would be a good way to be doing it though?

**Comment by vinkla** [comment]
We definitely need to find a way to speed things up. The fewer queries the better. 

I'm curious about your "patch". Any improvements are welcomed. How would your patch effect this package? Is it a breaking change? What you're saying is that you need to specify `with('translation`)` in order to fetch the translation?

**Comment by alexanderweiss** [comment]
I just created a pull request for locale caching; https://github.com/vinkla/translator/pull/31

For the translations I was suggesting to use with('translation') to eager load them. So when querying the database for say 60 items, of which you know you'll be needing the translation, you can eager load those translations (which Eloquent will then query for more efficiently that when querying for each of them on demand). Obviously this could only load them in the current locale. Also, it would not be required to load them this way, just a way to eager load them; adding one language to the cache right away (getTranslation should continue to query for translations if they aren't loaded yet).

**Comment by vinkla** [comment]
Cool, I'll check out your pull request. Keep up the good work! Really appreciate it.

Though, this would mean breaking the current setup to fetch translations? It would be really cool if everything was automated. Maybe we could add a option to the configuration file to specify if the developer wants to load the translations automatically or with eager loading. Since I guess this really depends on the project size.

Just to be clear, I'm not saying no. I would be cool to improve the speed. This new enhancement would be considered for an `3.0` release.

**Comment by alexanderweiss** [comment]
Thanks.

Well, no, I don't think it should break the current setup. Using with would just allow you to decide per search/query whether to eager load. But I'm not sure if it's possible. I'll probably try something out and post something here or create a pull request if I feel it might be a good solution. And feel free to reject it of course.

**Comment by vinkla** [comment]
Cool. Let me know when you find a good solution and we'll take it from there.

**Comment by uldisrudzitis** [comment]
I'm sure you know this package https://github.com/Anahkiasen/polyglot
There is a method Article::withLang()->get() to get model with translations.
Unfortunately it's not for L5, but maybe you can take the idea?

**Comment by vinkla** [comment]
@uldisrudzitis Haven't looked at it, no. Is it any good? It seems it basically does the same as this package and what @alexanderweiss describes above?

**Comment by iUtvikler** [comment]
This might be a dumb suggestion. I have not had time to try out this lib yet, but what if you use the locale (i.e. no, se, en) as the primary key.

You could query the translations based on the locale instead of the locales id.. In basic cases you wouldn't even need the locale table..

**Comment by vinkla** [comment]
@iUtvikler Yeah, that is true. Haven't thought about that before. Thanks!

The reason we have it in the database is because we want to be able to add new locales from an admin UI or similar. Maybe we should add a default array of locales within the configuration file if the developer doesn't want to use the ones in the database.

**Comment by vinkla** [comment]
@alexanderweiss, I've started working on the next release of this package. What would you like to see integrated? Please see #52

**Comment by alexanderweiss** [comment]
I'll try to have a look as soon as possible.

Thanks!

**Comment by vinkla** [comment]
I've removed the locales table in version 3.0 and everything is cached.
