### ISSUE TITLE
Removing the translations model?

### ISSUE THREAD

**Issue by vinkla** [vinkla/translator#6]
This is a feature I'm not comfortable to answer. If we add the CRUD methods to our trait (#5). Do we really need to add a second model just for translations? Maybe we could just specify which table to fetch from in the base model?

We could fetch the needed data and configuration from our base model. Example below.

```php

class Article extends Eloquent {

	/**
	 * We could fetch the fillable attributes from our base model.
	 * 
	 * @var array
	 */
	protected $fillable = ['title'];

	/**
	 * The table to fetch translations from. As default we use the 
	 * singular name of our base model ending with '_translations'. 
	 * 
	 * @var string
	 */
	protected $translationsTable = 'article_translations';

}
```

Instead of setting the `$translator` variable we now use `$translationsTable` instead. Any input?

**Comment by broszies** [comment]
I (obviously) cant comment on the possible ramifications, which is probably what you need more than accolade. But I like the idea of dropping an otheriwse empty model, makes for clean code.

**Comment by vinkla** [comment]
@broszies Yes, definitely. Would be nice to remove it.

**Comment by elieandraos** [comment]
hello, 
i have tried your package, i managed to make it work. and I checked the example you published also on github. 
My concern is in the create/update forms and their controller methods (imagine a crud operations to add/edit a news model that its title and desc fields are translatable). again i managed to make it work, but technically, what i did is : 

create a form with a text field for every translatable property in the news model (title,body) as so: 

```
//$locales is queried and passed to the view
@foreach($locales as $locale)	
		<h1>Content {{ $locale}}</h1>			
		<div>
			{!! Form::label('title_'.$locale, 'Title') !!}        
	               {!! Form::text('title_'.$locale, null) !!}
		</div>
		<div>
			{!! Form::label('body_'.$locale, 'Body') !!}        
	        {!! Form::textarea('body_'.$locale, null) !!}
		</div>
@endforeach
```

(that means the 'title', and 'body' fillable properties in my news model won't match anymore my POST values,so i won't be able to use it directly in my create([]) model method or even a validation request as the names have changed)

and in my create() method, i create the news for my default locale ('en') and update the news object with the remaining locales as follows
```
public function store()
	{
		$locales = Locale::where('language', '!=', 'en')->lists('language', 'id');
		$values = Input::all(); //original post values

		//save the news in 'en' locale
		$input = [
				'title' => $values['title_en'],
				'body'  => $values['body_en'],
				'image' => $values['image']
			];
		$news = News::create($input);
		//save the other locale values
		foreach($locales as $locale)
		{
			App::setLocale($locale);
			$input = [
				'title' => $values['title_'.$locale],
				'body'  => $values['body_'.$locale]
			];
			$news->update($input);
		}
		App::setLocale('en');
		return redirect('news');
	}
```

All of this works just so fine, but i think i am missing something, it just seems a very complicated pattern.
shouldn't the saving be a simple $news->create($input); without filtering the post array, is there a naming convention for the form inputs, or maybe add the eloquent relations in the translation model and then have something like 

```
$news->newsTranslations()->saveMany($newsTranslations); 
```

Appreciate your response, 
Cheers,

**Comment by vinkla** [comment]
@elieandraos Is this a similar question the #36? If not, please explain a bit more.

**Comment by elieandraos** [comment]
@vinkla no no this one was different... and a change of front end UI saved me :) 
what i was facing was the following:
- my news model is translatable to 2 other languages (3 locales in total) 
- initially i was trying to do the create in one global form (tabs for the other locales with inputs of the translatable fields respectively)

but then i faced the problem of inputs html name attribute, (i will have three inputs named title, for example: title_en, title_fr, title_es) or even 'title[]' and by that the create() model method won't work or the validation request, because the form inputs names are different then the model fillable properties (title) so i had to filter the inputs and loop through it and stuff, it was a pain in the ass. 

so i decided to change the ui, one form per locale, and by that keep the model/form mechanism simple  as the laravel flow, and also, that would make the validation request work too. 

i am sorry, i bugged you with my questions, i was trying the package and took me little time to understand the whole flow. 
you can close this issue, well maybe, update the docs of your example repos, that it is better to have a form per locale for basic crud operations, 

Cheers again, 
Thanks
